name: concurrent_revisions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.1

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: shards install
    - name: Run tests
      run: crystal spec spec/concurrent_revisions_spec.cr